version: '3.8'

services:
  web:
    build: .
    container_name: mots-ig-web
    ports:
      - "8123:80"
    volumes:
      - .:/var/www/html
    networks:
      - db_network
    restart: unless-stopped
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=20M
      - PHP_POST_MAX_SIZE=25M

networks:
  db_network:
    external: true
    name: db_master_shared
